# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    badge.service:
      class: AppBundle\DomainModel\BadgeService
      arguments: [ "@doctrine.orm.entity_manager" ]
    user.service:
      class: AppBundle\DomainModel\UserService
      arguments: [ "@doctrine.orm.entity_manager" ]

    app.form.registration:
      class: AppBundle\Form\RegistrationType
      tags:
        - { name: form.type, alias: app_user_registration }


